### ISSUE TITLE
请问您在什么数据上进行评测的？

### ISSUE THREAD

**Issue by JackWangCS** [person-lee/IARNN#1]
你好，我目前真正学习QA系统，打算做一个中文的QA系统。想参考一下您实现的IARNN（Inner Attention based Recurrent Neural Networks for Answer Selection），请问现在的精度是在哪一个评测集上运行的？
抱歉，仔细看了代码，能不能提供一下insuranceQA预处理后的训练数据吗

**Comment by person-lee** [comment]
insurace_qa数据集上,地址在(https://github.com/person-lee/insuranceQA)

**Comment by JackWangCS** [comment]
Thanks very much!
